export const frontActions = {
    GET_ARTICLE_LIST: 'GET_ARTICLE_LIST',
    RESPONSE_ARTICLE_LIST: "RESPONSE_ARTICLE_LIST",
    GET_ARTICLE_DETAIL: "GET_ARTICLE_DETAIL",
    RESPONSE_ARTICLE_DETAIL: "RESPONSE_ARTICLE_DETAIL"
}
export const defaultActions = {
    FETCH_START: "FETCH_START",
    FETCH_END: "FETCH_END",
    USER_LOGIN: "USER_LOGIN",
    USER_REGISTER: "USER_REGISTER",
    RESPONSE_USER_INFO: "RESPONSE_USER_INFO",
    SET_MESSAGE: "SET_MESSAGE",
    USER_AUTH: "USER_AUTH"
}

export const tagActions = {
    GET_ALL_TAGS: "GET_ALL_TAGS",
    SET_TAGS: "RESPONSE_GET_ALL_TAGS",
    DELETE_TAG: "DELETE_TAG",
    ADD_TAG: "ADD_TAG"
}

export const adminActions = {
    ADMIN_URI_LOCATION: "ADMIN_URI_LOCATION"
}

export const loginActions = {
    GOTO_SIGNIN: 'GOTO_SIGNIN',
    GOTO_SIGNUP: 'GOTO_SIGNUP',
    SIGNUP_REQ: 'SIGNUP_REQ',
    SIGNUP_RES: 'SIGNUP_RES',
    SIGNIN: 'SIGNIN',
}