export const frontActions = {
  GET_ARTICLE_LIST: 'GET_ARTICLE_LIST',
  GET_ARTICLE_LIST_RES: 'RESPONSE_ARTICLE_LIST',
  GET_ARTICLE_DETAIL: 'GET_ARTICLE_DETAIL',
  GET_ARTICLE_DETAIL_RES: 'RESPONSE_ARTICLE_DETAIL',
  GET_ALL_TAGS: 'GET_ALL_TAGS',
  GET_ALL_TAGS_RES: 'GET_ALL_TAGS_RES',
};
export const defaultActions = {
  FETCH_START: 'FETCH_START',
  FETCH_END: 'FETCH_END',
  SET_MESSAGE: 'SET_MESSAGE',
};


export const adminActions = {
  ADMIN_URI_LOCATION: 'ADMIN_URI_LOCATION',
};

export const loginActions = {
  GOTO_SIGNIN: 'GOTO_SIGNIN',
  GOTO_SIGNUP: 'GOTO_SIGNUP',
  SIGNUPORIN_REQ: 'SIGNUPORIN_REQ',
  SIGNUPORIN_RES: 'SIGNUPORIN_RES',
  PROVIDE_API: 'PROVIDE_API',
};

export const manageActions = {
  MANAGE_RES: 'MANAGE_RES',
  MANAGE_GET_ALL_REQ: 'MANAGE_GET_ALL_REQ',
  MANAGE_GET_REQ: 'MANAGE_GET_REQ',
  MANAGE_CREATE_REQ: 'MANAGE_CREATE_REQ',
  MANAGE_SET_REQ: 'MANAGE_SET_REQ',
  MANAGE_DELETE_REQ: 'MANAGE_DELETE_REQ',
  MANAGE_PROVIDE_API: 'MANAGE_PROVIDE_API',
  MANAGE_LOGOUT: 'MANAGE_LOGOUT',
  MANAGE_RELATIVE_DELETE: 'MANAGE_RELATIVE_DELETE',
  MANAGE_RESET:'MANAGE_RESET',
};